import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, GoogleAuthProvider, signInWithPopup, signInWithRedirect, sendPasswordResetEmail, signOut, updateProfile } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import { getFirestore, collection, query, orderBy, limit, getDocs, doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-functions.js';
import { firebaseConfig, functionsRegion } from './firebase-config.js';
const $=id=>document.getElementById(id);
const configured=firebaseConfig.apiKey!=='PASTE_API_KEY' && firebaseConfig.projectId!=='YOUR_PROJECT';
let auth,db,functions,user=null,challenge=null,busy=false;
const show=(s)=>$('authStatus').textContent=s;
const friendly=(e)=>({'auth/email-already-in-use':'Bu email ro‘yxatdan o‘tgan.','auth/invalid-email':'Email noto‘g‘ri.','auth/invalid-credential':'Email yoki parol noto‘g‘ri.','auth/weak-password':'Parol kamida 6 belgidan iborat bo‘lsin.','auth/unauthorized-domain':'Sayt domenini Firebase Authentication sozlamalariga qo‘shing.','functions/unauthenticated':'Avval akkauntga kiring.','functions/resource-exhausted':'Biroz kutib, qayta urinib ko‘ring.'}[e.code]||e.message||'Xatolik yuz berdi');
$('accountBtn').onclick=()=>{$('authOverlay').classList.remove('hidden');show(user?'Akkauntingiz: '+(user.displayName||user.email):'Kirish yoki ro‘yxatdan o‘tish')};
$('authClose').onclick=()=>$('authOverlay').classList.add('hidden');
$('authOverlay').onclick=e=>{if(e.target===$('authOverlay'))$('authOverlay').classList.add('hidden')};
$('arenaForm').onsubmit=async e=>{e.preventDefault();if(!user||!challenge||busy)return;busy=true;const btn=$('arenaForm button');btn.disabled=true;try{const response=await httpsCallable(functions,'submitArenaAnswer')({challengeId:challenge.id,answer:Number($('arenaAnswer').value)});const result=response.data;$('arenaFeedback').textContent=result.correct?'✓ To‘g‘ri! +10 global XP 🎉':`Javob: ${result.correctAnswer}. Yana urinib ko‘ring!`;$('arenaFeedback').className='feedback '+(result.correct?'ok':'bad');challenge=null;$('arenaQuestion').textContent='Yangi savolni bosing';await refreshBoard()}catch(err){$('arenaFeedback').textContent=friendly(err)}finally{busy=false;btn.disabled=false}};
async function newChallenge(){if(!user){$('arenaStatus').textContent='Global Arena uchun akkauntga kiring.';return}if(busy)return;busy=true;$('arenaNext').disabled=true;try{const r=await httpsCallable(functions,'createArenaChallenge')({});challenge=r.data;$('arenaQuestion').textContent=challenge.question;$('arenaAnswer').value='';$('arenaFeedback').textContent='';$('arenaStatus').textContent='Savolni yeching — +10 global XP';}catch(err){$('arenaStatus').textContent=friendly(err)}finally{busy=false;$('arenaNext').disabled=false}}
$('arenaNext').onclick=newChallenge;
async function refreshBoard(){if(!db)return;$('leaderboard').textContent='Yuklanmoqda...';try{const snap=await getDocs(query(collection(db,'leaderboard'),orderBy('xp','desc'),limit(50)));const box=$('leaderboard');box.replaceChildren();let rank=0;let found=false;snap.forEach(item=>{rank++;const data=item.data();const row=document.createElement('div');row.className='leaderboard-row'+(user&&item.id===user.uid?' me':'');const pos=document.createElement('span');pos.textContent=rank<=3?['🥇','🥈','🥉'][rank-1]:String(rank);const name=document.createElement('span');name.textContent=String(data.nickname||'Matematik').slice(0,20);const xp=document.createElement('strong');xp.textContent=Number(data.xp||0)+' XP';row.append(pos,name,xp);box.append(row);if(user&&item.id===user.uid)found=true});if(!rank)box.textContent='Hozircha reyting bo‘sh. Birinchi bo‘ling!';$('myGlobalRank').textContent=!user?'Akkauntga kiring':found?'Siz TOP 50 ichidasiz!':'TOP 50 ga kirish uchun Arena o‘ynang.'}catch(err){$('leaderboard').textContent=friendly(err)}}
$('refreshLeaderboard').onclick=refreshBoard;
if(!configured){show('firebase-config.js fayliga Firebase ma’lumotlarini kiriting.');$('arenaStatus').textContent='Firebase ulanmagan. README.md yo‘riqnomasiga qarang.';$('leaderboard').textContent='Firebase sozlanmagan.';$('authForm').onsubmit=e=>{e.preventDefault();show('Avval Firebase konfiguratsiyasini kiriting.')};}else{
try{
const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);functions=getFunctions(app,functionsRegion);
const profile=async nickname=>{await httpsCallable(functions,'ensureProfile')({nickname});};
$('authForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('authEmail').value.trim(),$('authPassword').value);$('authOverlay').classList.add('hidden')}catch(err){show(friendly(err))}};
$('signupBtn').onclick=async()=>{const nickname=$('authNickname').value.trim();if(!/^[\p{L}\p{N}_ .-]{3,20}$/u.test(nickname)){show('3–20 belgili taxallus kiriting.');return}if(!$('authEmail').validity.valid||$('authPassword').value.length<6){show('Email va kamida 6 belgili parol kiriting.');return}try{const cred=await createUserWithEmailAndPassword(auth,$('authEmail').value.trim(),$('authPassword').value);await updateProfile(cred.user,{displayName:nickname});await profile(nickname);$('authOverlay').classList.add('hidden')}catch(err){show(friendly(err))}};
$('googleBtn').onclick=async()=>{try{const cred=await signInWithPopup(auth,new GoogleAuthProvider());await profile(cred.user.displayName?.replace(/[^\p{L}\p{N}_ .-]/gu,'').slice(0,20)||'Matematik');$('authOverlay').classList.add('hidden')}catch(err){if(err.code==='auth/popup-blocked'){await signInWithRedirect(auth,new GoogleAuthProvider())}else show(friendly(err))}};
$('resetPasswordBtn').onclick=async()=>{if(!$('authEmail').value){show('Avval emailingizni kiriting.');return}try{await sendPasswordResetEmail(auth,$('authEmail').value.trim());show('Agar email ro‘yxatda bo‘lsa, tiklash xati yuboriladi.')}catch(err){show(friendly(err))}};
$('logoutBtn').onclick=async()=>{await signOut(auth);$('authOverlay').classList.add('hidden')};
onAuthStateChanged(auth,async current=>{user=current;$('logoutBtn').classList.toggle('hidden',!user);$('authForm').classList.toggle('hidden',!!user);$('googleBtn').classList.toggle('hidden',!!user);$('resetPasswordBtn').classList.toggle('hidden',!!user);$('accountBtn').textContent=user?'🟢':'👤';$('sideName').textContent=user?(user.displayName||'Matematik').slice(0,20):'Mehmon';if(user){try{await profile(user.displayName?.replace(/[^\p{L}\p{N}_ .-]/gu,'').slice(0,20)||'Matematik')}catch(err){console.warn('Profile:',friendly(err))}newChallenge()}else{$('arenaStatus').textContent='Akkauntga kirib global XP to‘plang.';$('arenaQuestion').textContent='? + ?';challenge=null}refreshBoard()});
}catch(err){show('Firebase ulanishida xato: '+friendly(err));$('arenaStatus').textContent='Firebase ulanmadi.'}
}
