'use strict';
const $=id=>document.getElementById(id);
const lessons=[
['🔢','Sonlar olami','0 dan 100 gacha sonlar va taqqoslash',['Sonlar miqdorni ifodalaydi. 0 — hech narsa yo‘qligini bildiradi.','Natural sonlar: 1, 2, 3, 4 va hokazo.','Katta son >, kichik son < belgisi bilan taqqoslanadi.'],'4 < 7\n9 > 3\n5 = 5','8 va 12 dan kattasi qaysi?','12','12 soni 8 dan katta.'],
['➕','Qo‘shish','Sonlarni birlashtirish va yig‘indi',['Qo‘shish — sonlarni birlashtirish amali.','Qo‘shiluvchilarning o‘rnini almashtirish natijani o‘zgartirmaydi.','Nol qo‘shilsa, son o‘zgarmaydi.'],'3 + 4 = 7\n4 + 3 = 7\n8 + 0 = 8','9 + 6 = ?','15','9 ga 6 qo‘shilsa 15.'],
['➖','Ayirish','Farqni topish va teskari amal',['Ayirish — bir miqdordan ikkinchisini olish.','Ayirish qo‘shishning teskari amalidir.','Sonning o‘zidan o‘zi ayrilsa, 0 qoladi.'],'12 − 5 = 7\n7 + 5 = 12','17 − 9 = ?','8','17 dan 9 ayirilsa 8.'],
['✖️','Ko‘paytirish','Takroriy qo‘shish va jadval',['Ko‘paytirish bir xil sonlarni takror qo‘shishdir.','a × b — a sonini b marta qo‘shish.','Istalgan sonni 0 ga ko‘paytirsak, 0 bo‘ladi.'],'4 × 3 = 4 + 4 + 4 = 12','7 × 8 = ?','56','7 ni 8 marta qo‘shsak 56.'],
['➗','Bo‘lish','Teng qismlarga ajratish',['Bo‘lish — miqdorni teng qismlarga ajratish.','Bo‘lish ko‘paytirishga teskari amal.','Nolga bo‘lish mumkin emas.'],'20 ÷ 4 = 5\n5 × 4 = 20','36 ÷ 6 = ?','6','36 ni 6 ta teng qismga bo‘lsak 6.'],
['🧩','Amallar tartibi','Qavslar va to‘rt amal',['Avval qavs ichidagi amallar bajariladi.','Keyin ko‘paytirish va bo‘lish chapdan o‘ngga.','Oxirida qo‘shish va ayirish chapdan o‘ngga.'],'3 + 2 × 5 = 13\n(3 + 2) × 5 = 25','4 + 3 × 6 = ?','22','Avval 3 × 6 = 18, keyin 4 + 18 = 22.'],
['½','Oddiy kasrlar','Surat, maxraj va teng qismlar',['Kasr butunning teng qismlarini ifodalaydi.','Yuqori son — surat, pastki son — maxraj.','Maxrajlari teng kasrlarni qo‘shganda suratlar qo‘shiladi.'],'1/5 + 2/5 = 3/5','2/7 + 3/7 = ?','5/7','Suratlar: 2 + 3 = 5; maxraj 7 qoladi.'],
['🔟','O‘nli kasrlar','Vergulli sonlar bilan amallar',['O‘nli kasrlar o‘ndan, yuzdan birlarni ko‘rsatadi.','Qo‘shishda vergullar bir ustunda bo‘lishi kerak.','0,5 = 1/2.'],'1,2 + 0,3 = 1,5','2,5 + 1,4 = ?','3,9','2,5 + 1,4 = 3,9.'],
['💯','Foizlar','100 dan ulushni hisoblash',['1% — butunning yuzdan bir qismi.','50% — yarmi, 25% — choragi.','Sonning foizini topish: son × foiz / 100.'],'200 ning 10% i = 20','80 ning 25% i = ?','20','80 × 25 / 100 = 20.'],
['📐','Geometriya','Shakllar, perimetr va yuza',['Kvadratning 4 tomoni teng.','To‘g‘ri to‘rtburchak yuzi: uzunlik × kenglik.','Kvadrat perimetri: 4 × tomon.'],'Tomoni 5 bo‘lgan kvadrat perimetri = 20','Tomoni 7 bo‘lgan kvadrat perimetri?','28','4 × 7 = 28.'],
['❓','Tenglamalar','Noma’lum sonni topish',['Tenglamada noma’lum son ko‘pincha x bilan belgilanadi.','Tenglikning ikki tomoniga bir xil amal qo‘llash mumkin.','Javobni asl tenglamaga qo‘yib tekshiring.'],'x + 7 = 15 → x = 8','x + 13 = 29. x = ?','16','29 − 13 = 16.'],
['📈','Funksiyalarga kirish','Bog‘lanish va koordinatalar',['Funksiya bir miqdorning boshqasiga bog‘liqligini ifodalaydi.','y = 2x bo‘lsa, x o‘zgarganda y ham o‘zgaradi.','Grafikda nuqtalar (x; y) ko‘rinishida belgilanadi.'],'x = 3 → y = 2 × 3 = 6','y = 3x. x = 4 bo‘lsa, y = ?','12','3 × 4 = 12.']
];
const badges=[['🌱','Birinchi qadam','Birinchi darsni tugating',s=>s.done.length>=1],['✨','Bilim izlovchi','3 ta darsni tugating',s=>s.done.length>=3],['🎓','Matematika ustasi','12 ta darsni tugating',s=>s.done.length>=12],['⚡','Chaqqon','Math Battle’da 5 ball oling',s=>s.bestBattle>=5],['🔥','Izchil o‘quvchi','3 kun ketma-ket shug‘ullaning',s=>s.streak>=3],['💎','XP ustasi','500 XP to‘plang',s=>s.xp>=500],['🎯','Aniq nishon','Testda 100 ball oling',s=>s.bestQuiz>=100],['🏅','Mashq ustasi','50 ta to‘g‘ri javob',s=>s.correct>=50]];
const fresh=()=>({xp:0,done:[],correct:0,attempts:0,streak:0,lastDay:'',dailyDay:'',dailyCorrect:0,dailyClaimed:false,bestBattle:0,bestQuiz:0,quizzes:0,history:{}});
let state;try{state={...fresh(),...JSON.parse(localStorage.getItem('math_pro_2')||'{}')}}catch{state=fresh()};if(!Array.isArray(state.done))state.done=[];if(!state.history||typeof state.history!=='object')state.history={};
const day=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const previousDay=()=>{const d=new Date();d.setDate(d.getDate()-1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function touch(){const t=day();if(state.lastDay!==t){state.streak=state.lastDay===previousDay()?state.streak+1:1;state.lastDay=t}state.history[t]=(state.history[t]||0)+1}
function save(){try{localStorage.setItem('math_pro_2',JSON.stringify(state))}catch{}render()}
let toastTimer;function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800)}
let soundOn=localStorage.getItem('math_sound')==='on';let audioCtx;function beep(success=true){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);osc.type='sine';osc.frequency.value=success?740:230;gain.gain.setValueAtTime(.06,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.14);osc.start();osc.stop(audioCtx.currentTime+.15)}catch{}}
$('sound').onclick=()=>{soundOn=!soundOn;localStorage.setItem('math_sound',soundOn?'on':'off');$('sound').textContent=soundOn?'♫':'♪';notify(soundOn?'Ovoz yoqildi':'Ovoz o‘chirildi')};$('sound').textContent=soundOn?'♫':'♪';
let theme=localStorage.getItem('math_pro_theme')||'dark';function applyTheme(){document.body.classList.toggle('light',theme==='light');$('theme').textContent=theme==='light'?'☀':'☾'}$('theme').onclick=()=>{theme=theme==='light'?'dark':'light';localStorage.setItem('math_pro_theme',theme);applyTheme()};applyTheme();
function navigate(page){if(!$(page))return;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id===page));document.querySelectorAll('#nav button[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));const active=document.querySelector(`#nav button[data-page="${page}"]`);$('breadcrumb').textContent=active?active.textContent.trim():'Math Academy';$('sidebar').classList.remove('open');$('scrim').classList.remove('show');if(page==='map')renderMap();if(page==='achievements')renderBadges();if(page==='progress')renderProgress();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));$('menu').onclick=()=>{$('sidebar').classList.add('open');$('scrim').classList.add('show')};$('scrim').onclick=()=>{$('sidebar').classList.remove('open');$('scrim').classList.remove('show')};
const nextLesson=()=>Math.min(state.done.length,lessons.length-1);function render(){if(state.dailyDay!==day()){state.dailyDay=day();state.dailyCorrect=0;state.dailyClaimed=false;try{localStorage.setItem('math_pro_2',JSON.stringify(state))}catch{}}const level=Math.floor(state.xp/100)+1;$('xpTop').textContent=state.xp;$('streakTop').textContent=state.streak;$('sideLevel').textContent=`${level}-daraja`;$('homeXP').textContent=state.xp;$('homeStreak').textContent=state.streak;$('homeDone').textContent=state.done.length;$('homeBadges').textContent=badges.filter(b=>b[3](state)).length;$('todayDate').textContent=new Date().toLocaleDateString('uz-UZ',{day:'numeric',month:'long',year:'numeric'});const n=nextLesson();$('nextTitle').textContent=state.done.length===lessons.length?'Barcha darslar tugadi!':lessons[n][1];$('nextDesc').textContent=state.done.length===lessons.length?'Tabriklaymiz! Mashqlar bilan davom eting.':lessons[n][2];const percent=Math.round(state.done.length/lessons.length*100);$('courseProgress').style.width=percent+'%';$('coursePercent').textContent=percent+'% bajarildi';$('dailyCount').textContent=Math.min(state.dailyCorrect,5)+'/5';$('dailyProgress').style.width=Math.min(state.dailyCorrect/5*100,100)+'%';$('mapCompleted').textContent=`${state.done.length} / 12 dars`;$('mapBar').style.width=percent+'%';$('battleBest').textContent=state.bestBattle}
$('continueBtn').onclick=()=>{navigate('map');openLesson(nextLesson())};
function renderMap(){$('lessonGrid').innerHTML=lessons.map((l,i)=>{const done=state.done.includes(i),locked=i>0&&!state.done.includes(i-1);return `<article class="lesson-card ${locked?'locked':''}"><span class="lesson-number">BOSQICH ${String(i+1).padStart(2,'0')}</span><div class="lesson-icon">${l[0]}</div><h3>${l[1]}</h3><p>${l[2]}</p><div class="between"><span class="status">${done?'✓ O‘tilgan':locked?'🔒 Avvalgi darsni tugating':'+30 XP'}</span><button class="btn ${locked?'outline':'primary'}" data-lesson="${i}" ${locked?'disabled':''}>${done?'Qayta o‘qish':locked?'Yopiq':'Boshlash →'}</button></div></article>`}).join('');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(Number(b.dataset.lesson)))}
let currentLesson=-1;function openLesson(i){if(i>0&&!state.done.includes(i-1)){notify('Avval oldingi darsni tugating');return}currentLesson=i;const l=lessons[i];$('lessonDetail').innerHTML=`<span class="eyebrow">BOSQICH ${i+1}</span><h2>${l[0]} ${l[1]}</h2><p>${l[2]}</p><h3>📖 Nazariya</h3><ol>${l[3].map(t=>`<li>${t}</li>`).join('')}</ol><h3>💡 Misol</h3><div class="example">${l[4]}</div><h3>✍️ Mini-topshiriq</h3><p>${l[5]}</p><form class="answer-form" id="lessonForm"><input id="lessonInput" required autocomplete="off" placeholder="Javob" aria-label="Dars javobi"><button class="btn primary">Tekshirish ✓</button></form><p class="feedback" id="lessonFeedback" aria-live="polite"></p>`;$('lessonDetail').classList.remove('hidden');$('lessonForm').onsubmit=e=>{e.preventDefault();const normalize=x=>x.trim().replace(/\s/g,'').replace(',','.');const answer=normalize($('lessonInput').value),correct=normalize(l[6]);if(answer===correct||answer!==''&&Number.isFinite(Number(answer))&&Number(answer)===Number(correct)){$('lessonFeedback').className='feedback ok';$('lessonFeedback').textContent='✓ To‘g‘ri! '+l[7];beep();if(!state.done.includes(i)){state.done.push(i);state.done.sort((a,b)=>a-b);state.xp+=30;touch();save();renderMap();notify('Yangi dars tugadi! +30 XP 🎉')}}else{$('lessonFeedback').className='feedback bad';$('lessonFeedback').textContent='Yana urinib ko‘ring. Misolni diqqat bilan ko‘ring.';beep(false)}};$('lessonDetail').scrollIntoView({behavior:'smooth',block:'start'})}
const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;function question(difficulty='easy',op='mix'){const ops=['+','-','*','/'];if(op==='mix')op=ops[rand(0,3)];let a,b,answer;const lim=difficulty==='hard'?100:difficulty==='medium'?40:12;if(op==='+'){a=rand(1,lim);b=rand(1,lim);answer=a+b}else if(op==='-'){a=rand(1,lim);b=rand(1,lim);if(a<b)[a,b]=[b,a];answer=a-b}else if(op==='*'){a=rand(1,difficulty==='hard'?20:12);b=rand(1,difficulty==='easy'?5:12);answer=a*b}else{b=rand(1,difficulty==='hard'?20:12);answer=rand(1,difficulty==='easy'?5:12);a=b*answer}return{text:`${a} ${{'*':'×','/':'÷'}[op]||op} ${b} = ?`,answer}}
let currentProblem,answered=false;function newProblem(){currentProblem=question($('difficulty').value,$('operation').value);answered=false;$('problem').textContent=currentProblem.text;$('answer').value='';$('answer').disabled=false;$('practiceForm').querySelector('button').disabled=false;$('practiceFeedback').textContent='';$('practiceFeedback').className='feedback'}function recordCorrect(xp=10){state.xp+=xp;state.correct++;touch();if(state.dailyDay!==day()){state.dailyDay=day();state.dailyCorrect=0;state.dailyClaimed=false}state.dailyCorrect++;if(state.dailyCorrect>=5&&!state.dailyClaimed){state.dailyClaimed=true;state.xp+=30;notify('Kunlik missiya bajarildi! +30 bonus XP 🎉')}save()}
$('practiceForm').onsubmit=e=>{e.preventDefault();if(answered)return;answered=true;state.attempts++;const correct=Number($('answer').value)===currentProblem.answer;const fb=$('practiceFeedback');fb.className='feedback '+(correct?'ok':'bad');fb.textContent=correct?'Ajoyib! +10 XP 🎉':`To‘g‘ri javob: ${currentProblem.answer}. Yana urinib ko‘ring!`;beep(correct);if(correct)recordCorrect();else save();$('answer').disabled=true;$('practiceForm').querySelector('button').disabled=true};$('newProblem').onclick=newProblem;$('difficulty').onchange=newProblem;$('operation').onchange=newProblem;
let battleTimer=null,battleCurrent,battleScore=0,battleTime=60,battleRunning=false;function stopTimer(){if(battleTimer!==null){clearInterval(battleTimer);battleTimer=null}}function nextBattle(){battleCurrent=question('medium','mix');$('battleProblem').textContent=battleCurrent.text;$('battleAnswer').value='';$('battleAnswer').focus()}function startBattle(){stopTimer();battleTime=60;battleScore=0;battleRunning=true;$('battleIntro').classList.add('hidden');$('battleResult').classList.add('hidden');$('battleGame').classList.remove('hidden');$('battleScore').textContent=0;$('battleTime').textContent=60;$('battleBar').style.width='100%';$('battleFeedback').textContent='';nextBattle();battleTimer=setInterval(()=>{battleTime--;$('battleTime').textContent=battleTime;$('battleBar').style.width=battleTime/60*100+'%';if(battleTime<=0)finishBattle()},1000)}function finishBattle(){if(!battleRunning)return;battleRunning=false;stopTimer();state.bestBattle=Math.max(state.bestBattle,battleScore);save();$('battleGame').classList.add('hidden');$('battleResult').classList.remove('hidden');$('battleSummary').textContent=`Siz ${battleScore} ta misolni to‘g‘ri yechdingiz. Rekordingiz: ${state.bestBattle}.`}$('startBattle').onclick=startBattle;$('retryBattle').onclick=startBattle;$('stopBattle').onclick=finishBattle;$('battleForm').onsubmit=e=>{e.preventDefault();if(!battleRunning)return;state.attempts++;const correct=Number($('battleAnswer').value)===battleCurrent.answer;if(correct){battleScore++;recordCorrect(5)}else save();$('battleScore').textContent=battleScore;$('battleFeedback').textContent=correct?'✓ To‘g‘ri! +5 XP':'✕ Keyingisiga o‘tamiz!';$('battleFeedback').className='feedback '+(correct?'ok':'bad');beep(correct);nextBattle()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&battleRunning)finishBattle()});
let quizQuestions=[],quizIndex=0,quizPoints=0,quizAnswered=false;function options(answer){const s=new Set([answer]);while(s.size<4){const v=answer+rand(-12,12);if(v>=0)s.add(v)}return [...s].sort(()=>Math.random()-.5)}function startQuiz(){quizQuestions=Array.from({length:10},()=>{const q=question(Math.random()<.5?'easy':'medium');return {...q,options:options(q.answer)}});quizIndex=0;quizPoints=0;$('quizIntro').classList.add('hidden');$('quizResult').classList.add('hidden');$('quizGame').classList.remove('hidden');showQuiz()}function showQuiz(){quizAnswered=false;const q=quizQuestions[quizIndex];$('quizCount').textContent=`${quizIndex+1} / 10`;$('quizScore').textContent=quizPoints+' ball';$('quizBar').style.width=quizIndex*10+'%';$('quizQuestion').textContent=q.text;$('quizFeedback').textContent='';$('nextQuiz').classList.add('hidden');$('quizOptions').innerHTML='';q.options.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>answerQuiz(v);$('quizOptions').appendChild(b)})}function answerQuiz(v){if(quizAnswered)return;quizAnswered=true;const q=quizQuestions[quizIndex],correct=v===q.answer;state.attempts++;if(correct){quizPoints+=10;recordCorrect(10)}else save();document.querySelectorAll('#quizOptions button').forEach(b=>{b.disabled=true;if(Number(b.textContent)===q.answer)b.classList.add('correct');else if(Number(b.textContent)===v)b.classList.add('wrong')});$('quizFeedback').textContent=correct?'✓ Ajoyib! +10 XP':`To‘g‘ri javob: ${q.answer}`;$('quizFeedback').className='feedback '+(correct?'ok':'bad');beep(correct);$('quizScore').textContent=quizPoints+' ball';$('nextQuiz').textContent=quizIndex===9?'Natijani ko‘rish →':'Keyingi savol →';$('nextQuiz').classList.remove('hidden')}function finishQuiz(){state.quizzes++;state.bestQuiz=Math.max(state.bestQuiz,quizPoints);save();$('quizGame').classList.add('hidden');$('quizResult').classList.remove('hidden');$('quizSummary').textContent=`Siz 100 balldan ${quizPoints} ball to‘pladingiz! Shaxsiy rekordingiz: ${state.bestQuiz}/100.`}$('startQuiz').onclick=startQuiz;$('retryQuiz').onclick=startQuiz;$('nextQuiz').onclick=()=>{quizIndex++;quizIndex<10?showQuiz():finishQuiz()};
function renderBadges(){$('badgeGrid').innerHTML=badges.map(b=>{const unlocked=b[3](state);return `<article class="badge-card ${unlocked?'':'locked'}"><div class="badge-emoji">${b[0]}</div><h3>${b[1]}</h3><p>${b[2]}</p><span class="status">${unlocked?'✓ Qo‘lga kiritilgan':'🔒 Hali ochilmagan'}</span></article>`}).join('')}
function renderProgress(){const accuracy=state.attempts?Math.round(state.correct/state.attempts*100):0;const data=[['✦','Jami XP',state.xp],['🎓','Daraja',Math.floor(state.xp/100)+1],['✓','Aniqlik',accuracy+'%'],['🧠','Tugatilgan darslar',state.done.length],['⚡','Battle rekordi',state.bestBattle],['🎯','Eng yaxshi test',state.bestQuiz+'/100'],['✍️','Yechilgan savollar',state.attempts],['🏆','Medallar',badges.filter(b=>b[3](state)).length]];$('progressStats').innerHTML=data.map((x,i)=>`<article class="stat"><div class="stat-icon ${['violet','aqua','coral','gold'][i%4]}">${x[0]}</div><span>${x[1]}</span><strong>${x[2]}</strong></article>`).join('');$('levelText').textContent=`${state.xp%100}/100 XP — ${Math.floor(state.xp/100)+2}-darajagacha`;$('levelBar').style.width=state.xp%100+'%';let days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;days.push([d.toLocaleDateString('uz-UZ',{weekday:'short'}),state.history[key]||0])}const max=Math.max(1,...days.map(x=>x[1]));$('weekChart').innerHTML=days.map(([label,value])=>`<div class="week-item" title="${value} ta faollik"><div class="week-bar" style="height:${Math.max(5,value/max*95)}px"></div><small>${label}</small></div>`).join('')}
$('reset').onclick=()=>{if(!confirm('Barcha XP, darslar va rekordlar o‘chirilsinmi?'))return;state=fresh();save();renderMap();renderProgress();notify('Natijalar tozalandi')};
let expr='';function display(){ $('calcDisplay').textContent=expr.replace(/\*/g,'×').replace(/\//g,'÷')||'0'}function compute(s){const tokens=s.match(/(?:\d+(?:\.\d*)?|\.\d+|[+*/-])/g);if(!tokens||tokens.join('')!==s)throw Error('Noto‘g‘ri ifoda');const values=[];for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t==='-'&&(i===0||/[+*/-]/.test(tokens[i-1]))){const n=tokens[++i];if(!n||!/^\d*\.?\d+$/.test(n))throw Error('Noto‘g‘ri ifoda');values.push(-Number(n))}else if(/^\d*\.?\d+$/.test(t))values.push(Number(t));else values.push(t)}for(let i=1;i<values.length-1;){if(values[i]==='*'||values[i]==='/'){const v=values[i]==='*'?values[i-1]*values[i+1]:values[i-1]/values[i+1];if(!Number.isFinite(v))throw Error('Nolga bo‘lish mumkin emas');values.splice(i-1,3,v);i=1}else i+=2}let result=values[0];for(let i=1;i<values.length;i+=2){if(values[i]==='+')result+=values[i+1];else if(values[i]==='-')result-=values[i+1];else throw Error('Noto‘g‘ri ifoda')}if(!Number.isFinite(result))throw Error('Hisoblash xatosi');return String(Number(result.toPrecision(12)))}$('calcKeys').onclick=e=>{const b=e.target.closest('[data-key]');if(!b)return;const k=b.dataset.key;if(k==='AC')expr='';else if(k==='DEL')expr=expr.slice(0,-1);else if(k==='='){try{expr=compute(expr)}catch(err){notify(err.message)}}else if(k==='%'){if(/^-?\d+(\.\d+)?$/.test(expr))expr=String(Number(expr)/100)}else if(k==='±'){if(/^-?\d+(\.\d+)?$/.test(expr))expr=String(-Number(expr))}else if(/[+*/-]/.test(k)){if(!expr&&k!=='-')return;if(/[+*/-]$/.test(expr)&&k!=='-')expr=expr.slice(0,-1);expr+=k}else if(k==='.'){const n=expr.split(/[+*/-]/).pop();if(n.includes('.'))return;expr+=n?'.':'0.'}else expr+=k;display()};
render();renderMap();newProblem();navigate('home');
